version: "3.2"

networks:
  web:
    external: true
  internal:
    external: false

services:
  # Web-server
  nginx:
    image: nginx:${NGINX_VERSION}
    networks:
      - web
      - internal
    links:
      - php
    volumes:
      - ${PUBLIC_HTML}/:/var/www/html/
      - ${PUBLIC_FILES}/:/var/www/files/
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    container_name: nginx
    labels:
      - traefik.backend=nginx-webserver
      - traefik.frontend.rule=Host:${HOSTNAME}
      - traefik.docker.network=web
      - traefik.port=80
  
  # PHP-FPM for Nginx
  php:
    build:
      context: './docker/php'
      args:
        PHP_VERSION: ${PHP_VERSION}
    networks:
      - internal
    volumes:
      - ${PUBLIC_HTML}/:/var/www/html/
      - ${PUBLIC_FILES}/:/var/www/files/
    environment: 
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    container_name: php
    labels:
      - traefik.enable=false

  # MySQL 
  mysql:
    image: mysql:${MYSQL_VERSION:-latest}
    restart: always
    networks:
      - internal
    depends_on: 
      - php
    volumes:
      - data:/var/lib/mysql
      - ./db:/docker-entrypoint-initdb.d
    environment: 
      MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"
      MYSQL_DATABASE: "${DB_NAME}"
      MYSQL_USER: "${DB_USERNAME}"
      MYSQL_PASSWORD: "${DB_PASSWORD}"
    container_name: mysql
    labels:
      - traefik.enable=false

  # Temp MySQL console (For development purposes only)
  # phpmyadmin:
  #   image: phpmyadmin/phpmyadmin
  #   container_name: phpmyadmin
  #   depends_on:
  #     - mysql
  #   networks:
  #     - backend
  #   ports:
  #     - 8181:80
  #   environment:
  #     MYSQL_USERNAME: root
  #     MYSQL_PASSWORD: "${DB_ROOT_PASSWORD}"
  #     PMA_ARBITRARY: 1
  #     PMA_HOST: mysql
  #     PMA_USER: root
  #     PMA_PASSWORD: "${DB_ROOT_PASSWORD}"
  #     PMA_PORT: 3306

volumes:
    data:
