version: "3.2"
services:
  # Add traefik for load-balacing and Lets Encrypt certificate issuing.
  # If you are running multiple containers from the same host, consider making this standalone.
  traefik:
    image: traefik:alpine
    restart: always
    command: --web -c /etc/traefik/traefik.toml --LOGLEVEL=debug
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./docker/traefik/traefik.toml:/etc/traefik/traefik.toml
      - /acme

  # Nginx as the web-server. (Static files)
  nginx:
    image: nginx:${NGINX_VERSION}
    networks:
      - frontend
      - backend
    links:
      - php
    volumes:
      - ${PROJECT_ROOT}/:/var/www/html/
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    container_name: nginx
    labels:
      - "traefik.enable=true"
      - 'traefik.frontend.rule=Host:fmlab.no'
      - "traefik.port=80"

  php:
    build:
      context: './docker/php'
      args:
        PHP_VERSION: ${PHP_VERSION}
    networks:
      - backend
    volumes:
      - ${PROJECT_ROOT}/:/var/www/html/
    environment: 
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    container_name: php

  mysql:
    image: mysql:${MYSQL_VERSION:-latest}
    restart: always
    networks:
      - backend
    # ports:
    #   - 3306:3306
    depends_on: 
      - php
    volumes:
      - data:/var/lib/mysql
      - ./db:/docker-entrypoint-initdb.d
    environment: 
      MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"
      MYSQL_DATABASE: "${DB_NAME}"
      MYSQL_USER: "${DB_USERNAME}"
      MYSQL_PASSWORD: "${DB_PASSWORD}"
    container_name: mysql

  # Temp MySQL console (For development purposes only)
  # phpmyadmin:
  #   image: phpmyadmin/phpmyadmin
  #   container_name: phpmyadmin
  #   depends_on:
  #     - mysql
  #   networks:
  #     - backend
  #   ports:
  #     - 8181:80
  #   environment:
  #     MYSQL_USERNAME: root
  #     MYSQL_PASSWORD: "${DB_ROOT_PASSWORD}"
  #     PMA_ARBITRARY: 1
  #     PMA_HOST: mysql
  #     PMA_USER: root
  #     PMA_PASSWORD: "${DB_ROOT_PASSWORD}"
  #     PMA_PORT: 3306

networks:
  frontend:
  backend:

volumes:
    data:
